### ISSUE TITLE
White LED flashing, possible hardware issue

### ISSUE THREAD

**Issue by BentleySettin** [TinyCamML/Flood-Model#9]
I noticed after a few minutes the openMV led starts flashing white which apparently means "the firmware on the board panicking because there's a hardware failure." This happened twice when I removed the battery and then added it again. However when I unplugged boron and then replugged it into usb the issue has not happened since and it has been about 10 minutes. 

Not a consistent issue but something is wrong. Possible the HIGH to LOW voltage changes happening twice instead of once now?

**Comment by BentleySettin** [comment]
This issue is no longer present. I did not change anything so may have been an overload?

**Comment by SUPScientist** [comment]
Following up from email where @BentleySettin writes, "The LiPo and battery worked well and was successful. The white light did begin flashing again so I am going to charge the battery."

Did the white light on the OpenMV flash while the USB cable was still plugged in? If so, it wasn't likely a battery charging problem because having the USB cable plugged in actively charges the battery. There must be something else going on and it seems important to isolate the issue.

Moving this back to "in progress" as it may not be minor!

**Comment by BentleySettin** [comment]
Yes, the white light on the OpenMV flashed white while USB was still plugged in. Agreed.

**Comment by BentleySettin** [comment]
Changed openMV Camera
